### ISSUE TITLE
Extend order is wrong

### ISSUE THREAD

**Issue by ProLoser** [neoziro/angular-notification#1]
I may pick up this lib, but I noticed that you seem to be extending the options in the wrong order. Your "defaults" are overriding explicitly passed options:

https://github.com/neoziro/angular-notification/blob/master/angular-notification.js#L50

Shouldn't this be the other way around? Where options are last, your hard-coded default is first, and the provider defaults are in the middle?

**Comment by neoziro** [comment]
Fixed in v1.0.0.
