### ISSUE TITLE
settings default options does not work

### ISSUE THREAD

**Issue by webattitude** [neoziro/angular-notification#14]
Hello,
I tried to set a default option in a controller, but $notificationProvider.setOptions() throws an error : 
```
TypeError: $notificationProvider.setOptions is not a function
```

https://github.com/neoziro/angular-notification#notificationprovidersetoptionsoptions

**Comment by neoziro** [comment]
@webattitude I am very surprised because this option is used in tests and it works (https://github.com/neoziro/angular-notification/blob/master/test/angular-notification.js#L9). Can you tell me if you have solved your problem?

**Comment by webattitude** [comment]
Hi, how are tests supposed to be launched ?
I'm using $notificationProvider within a controller : 
```
    angular.module('myApp', ['notification'])
            .controller('MyController', function ($scope, $notification, $log, $window) {
                var p = [];
                console.log($notificationProvider.setOptions);
                $notificationProvider.setOptions({foo:'bar'});
```
but console.log() output is undefined...

**Comment by neoziro** [comment]
@webattitude controllers are only available in config in AngularJS.

**Comment by webattitude** [comment]
ok... sorry
anyway : 
```
    angular.module('myApp', ['notification'])
            .config(["$notificationProvider", function($notificationProvider) {
                $notificationProvider.setOptions({foo:'bar'});
            }])
            .controller('MyController', function ($scope, $notification, $log, $window) {

```

then I have : 
```
                    notification.$on('show', function (notif) {
                        $log.debug('My notification is displayed.');
                        $log.debug(notif);
                    });
```
but no _foo_ property while debugging `notif`...

**Comment by webattitude** [comment]
Ok, sorry to bother. I've come to understand custom options are not conserved.
It is now working, thank you very much.
