### ISSUE TITLE
Rename module / service

### ISSUE THREAD

**Issue by ProLoser** [neoziro/angular-notification#2]
Since the native api of `window.Notification` can actually be accessed by doing `Notification` (I'm aware this is bad practice) it would be more suitable to perhaps rename your service to `$notification` which would help us distinguish the angular-wrapped version. This would also allow ng app developers to use the `Notification` provider name without conflicting with the one you provide in your library. For the same reason you may want to consider namespacing your module name with something like `angular-notification` or `ng-notification` or `nz-notifcation`

**Comment by neoziro** [comment]
Done.
