### ISSUE TITLE
Return promise instead callback

### ISSUE THREAD

**Issue by davinkevin** [neoziro/angular-notification#4]
Hi, 

First, thanks for your lib, I really like it :+1: 

It could be useful to have the possibility to use promise instead callback in the 'requestPermission' function.
Including $q will trigger a full digest-cycle and let our app react to this change.

I have wrapped up the notification service inside one of my directive controller (write in es6) : 
```js
notificationPromise() {
        let deferred = this.$q.defer();
        this.Notification.requestPermission(() => {
            deferred.resolve();
        });
        return deferred.promise;
    }
```
--> Full source code here : [authorize-notification](https://github.com/davinkevin/Podcast-Server/blob/de1344d1f6e44b111423ca87e28e17cc25557938/src/main/webapp/app/js/modules/common/authorize-notification.es6.js#L30)

**Comment by neoziro** [comment]
@davinkevin I can't see the code, but feel free to make a PR and I will merge it. Thanks.

**Comment by davinkevin** [comment]
Correction of the link... but everything is in the example.

I'll try to make a PR to this feature.

Thanks to see you still monitoring the repo

**Comment by davinkevin** [comment]
Modificaiton done in https://github.com/davinkevin/angular-notification/commit/251ceac5904f06883fe143044a6963c5e60078f8

I need to update the test... and i am not familiar with the Sinon.js framework, especially for handling promise... 

I'll try to do my best, but if you want to check :+1:

**Comment by neoziro** [comment]
@davinkevin I am sorry but since you changed the indentation, everything has changed lol, it looks like a complete rewriting here!

**Comment by davinkevin** [comment]
Sorry for that, I didn't disable the auto-format before commit :disappointed: 

I've juste revert and add the modification without the indentation --> https://github.com/davinkevin/angular-notification/commit/c616378fbef4f3653b63b5958601b75599f92a65
