### ISSUE TITLE
Exception when using it on IE

### ISSUE THREAD

**Issue by robertaistleitner** [neoziro/angular-notification#7]
I know that IE doesn't support notifications, but the library doesn't show me that it doesn't support them, would be best to just ignore calls to it.

Currently the constructor just returns false (which has no effect in a constructor), but if you try to try to register a click listener via $on an exception is thrown because this._events is not initialized to an array.

There are multiple ways to fix this but it's an issue i think since i don't want to take care if the browser supports notifications.

PS: For the rest of the library: thumbs up!

**Comment by neoziro** [comment]
You should take care if the browser support notifications.. Wrap it in another service.
